# Site settings
title: Carson Tang blog
email: 
description: "Software engineering thoughts and advice"
baseurl: ""
url: "http://carsontang.github.io"
twitter_username: carsontang
github_username:  carsontang

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
